
exp_name: "REFUEL-1B-test"
training_method: REFUEL
seed: 555134
track: true
wandb_project_name: "multiturn_largebatch"
wandb_dir: null
run_name: null
print_sample_output_freq: 100
upload_interval: 2


# Optimizer settings
eps: 1e-8
lr: 3e-7
weight_decay: 1e-6
optimizer: "adamw"
warmup_ratio: 0.1
start_idx: 0
end_idx: -1

gradient_accumulation_steps: 1
per_device_train_batch_size: 1
per_device_eval_batch_size: 16
total_episodes: 1000

 
# Model paths
base_model: "meta-llama/Llama-3.2-1B-Instruct"
output_dir: "/cluster/scratch/fraluca/huggingface/models/"
dataset: "LuckyLukke/NEGOTIO_REFUEL_8B_1000_preprocessed2"

total_length: 2048
temperature: 0.8

# REFUEL-specific settings
refuel:
  whiten_rewards: false
  shift_mean: false
  eta: null
  beta: 0.1
  nll_term: False
  alpha: null