
exp_name: "DPO_3"
training_method: DPO
seed: 555134
track: true
wandb_project_name: "multiturn_largebatch"
run_name: null
wandb_dir: null
print_sample_output_freq: 500
upload_interval: 2500

# Optimizer settings
eps: 1e-8
lr: 3e-7
weight_decay: 1e-6
optimizer: "adamw"
warmup_ratio: 0.1
start_idx: 0
end_idx: -1

gradient_accumulation_steps: 1
per_device_train_batch_size: 4
per_device_eval_batch_size: 16
total_episodes: 15000

 
# Model paths
base_model: "meta-llama/Llama-3.1-8B-Instruct"
output_dir: "/cluster/scratch/fraluca/huggingface/models/"
dataset: "LuckyLukke/negotio_DPO_onesided_preprocessed"

total_length: 2048
temperature: 0.9

# DPO specific settings
dpo:
  beta: 0.1
  with_offset: false